const ROLES = {
  ADMIN: 'Admin',
  OPERATOR: 'Operator',
  APPROVER: 'Approver',
  SIGNER: 'Signer',
  AUDITOR: 'Auditor',
};

const DOSSIER_STATES = {
  UPLOAD: 'UPLOAD',
  VALIDATING: 'VALIDATING',
  VALIDATED: 'VALIDATED',
  APPROVED: 'APPROVED',
  PACKAGING: 'PACKAGING',
  PACKAGED: 'PACKAGED',
  DONE: 'DONE',
  REJECTED: 'REJECTED',
};

const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_LOCKED: 'USER_LOCKED',
  USER_UNLOCKED: 'USER_UNLOCKED',
  UPLOAD: 'UPLOAD',
  VALIDATE: 'VALIDATE',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  PACKAGE: 'PACKAGE',
  SIGN: 'SIGN',
  DOWNLOAD: 'DOWNLOAD',
};

module.exports = { ROLES, DOSSIER_STATES, AUDIT_ACTIONS };
